name: $(BuildID)-$(Build.SourceBranchName)

trigger:
- master
- develop

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Go@0
      displayName: build
      inputs:
        command: 'build'
        arguments: '-a -installsuffix cgo -o $(Build.ArtifactStagingDirectory)/main -v'
        workingDirectory: 'src/ITLabReports/api'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish build artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'itlab-reports-api-build'
        publishLocation: 'pipeline'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish deploy artifact'
      inputs:
        targetPath: 'deploy'
        artifact: 'itlab-reports-deploy'
        publishLocation: 'pipeline'

- stage: Test
  displayName: Test reports service
  jobs:
  - job: Test
    displayName: Test

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'itlab-reports-api-build'
        buildType: 'current'
        targetPath: './tests/e2e/api/itlab-reports-api-build'
    - task: CmdLine@2
      displayName: run testmace
      inputs:
        script: 'docker-compose --no-ansi up testmace'
        workingDirectory: './tests/e2e/'
    - task: CmdLine@2
      displayName: show logs
      inputs:
        script: 'docker-compose --no-ansi logs test-api'
        workingDirectory: './tests/e2e/'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'tests/e2e/out'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'testmace*.xml'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        failTaskOnFailedTests: true
