version: '3.8'
services:
  reports-back:
    image: rtuitlab/itlab-reports-back
    environment:
      - ITLAB_REPORTS_APP_PORT=5506
      - ITLAB_REPORTS_APP_TEST_MODE=false
      - ITLAB_REPORTS_AUTH_SCOPE=itlab.reports
      - ITLAB_REPORTS_AUTH_AUDIENCE=itlab
