version: "3.8"

services:
  test-api:
    build:
      context: "${BACK_PROJECTS_CONTEXT-.}/src/ITLabReports"
    depends_on:
      - test-db
    environment:
      - ITLAB_REPORTS_AUTH_KEY_URL=https://examplesite/files/jwks.json
      - ITLAB_REPORTS_AUTH_AUDIENCE=itlab
      - ITLAB_REPORTS_AUTH_ISSUER=https://exampleissuersite.com
      - ITLAB_REPORTS_AUTH_SCOPE=itlab.reports
      - ITLAB_REPORTS_MONGO_URI=mongodb://test-db:27017/ITLabReports
      - ITLAB_REPORTS_APP_PORT=8080
      - ITLAB_REPORTS_APP_TEST_MODE=true
      - ITLAB_REPORTS_ROLE_USER=user
      - ITLAB_REPORTS_ROLE_ADMIN=reports.admin
      - ITLAB_REPORTS_ROLE_SUPER_ADMIN=admin
    ports:
      - 8080:8080
  test-db:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: itlab-reports
