FROM golang:1.18 AS builder

WORKDIR /go/src/ITLabReports/

ENV CGO_ENABLED=0
COPY go.* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/main/main.go    

FROM alpine:latest  
WORKDIR /root/
COPY --from=builder /go/src/ITLabReports/main .

# See README to generate certificate
COPY certs/localhost.crt /usr/share/ca-certificates/localhost.crt
RUN apk update && apk add ca-certificates
RUN echo localhost.crt >> /etc/ca-certificates.conf
RUN update-ca-certificates

CMD ["./main"]