// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: rtuitlab/itlab/reports/v1/reports.proto

package services

import (
	types "github.com/RTUITLab/ITLab/proto/reports/types"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReportsServiceErrors int32

const (
	ReportsServiceErrors_REPORT_NOT_FOUND ReportsServiceErrors = 0
)

// Enum value maps for ReportsServiceErrors.
var (
	ReportsServiceErrors_name = map[int32]string{
		0: "REPORT_NOT_FOUND",
	}
	ReportsServiceErrors_value = map[string]int32{
		"REPORT_NOT_FOUND": 0,
	}
)

func (x ReportsServiceErrors) Enum() *ReportsServiceErrors {
	p := new(ReportsServiceErrors)
	*p = x
	return p
}

func (x ReportsServiceErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportsServiceErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_rtuitlab_itlab_reports_v1_reports_proto_enumTypes[0].Descriptor()
}

func (ReportsServiceErrors) Type() protoreflect.EnumType {
	return &file_rtuitlab_itlab_reports_v1_reports_proto_enumTypes[0]
}

func (x ReportsServiceErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportsServiceErrors.Descriptor instead.
func (ReportsServiceErrors) EnumDescriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP(), []int{0}
}

type GetReportImplementerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (x *GetReportImplementerReq) Reset() {
	*x = GetReportImplementerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportImplementerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportImplementerReq) ProtoMessage() {}

func (x *GetReportImplementerReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportImplementerReq.ProtoReflect.Descriptor instead.
func (*GetReportImplementerReq) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP(), []int{0}
}

func (x *GetReportImplementerReq) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetReportImplementerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*GetReportImplementerResp_Implementer
	//	*GetReportImplementerResp_Error
	Result isGetReportImplementerResp_Result `protobuf_oneof:"result"`
}

func (x *GetReportImplementerResp) Reset() {
	*x = GetReportImplementerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportImplementerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportImplementerResp) ProtoMessage() {}

func (x *GetReportImplementerResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportImplementerResp.ProtoReflect.Descriptor instead.
func (*GetReportImplementerResp) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP(), []int{1}
}

func (m *GetReportImplementerResp) GetResult() isGetReportImplementerResp_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetReportImplementerResp) GetImplementer() string {
	if x, ok := x.GetResult().(*GetReportImplementerResp_Implementer); ok {
		return x.Implementer
	}
	return ""
}

func (x *GetReportImplementerResp) GetError() ReportsServiceErrors {
	if x, ok := x.GetResult().(*GetReportImplementerResp_Error); ok {
		return x.Error
	}
	return ReportsServiceErrors_REPORT_NOT_FOUND
}

type isGetReportImplementerResp_Result interface {
	isGetReportImplementerResp_Result()
}

type GetReportImplementerResp_Implementer struct {
	Implementer string `protobuf:"bytes,1,opt,name=implementer,proto3,oneof"`
}

type GetReportImplementerResp_Error struct {
	Error ReportsServiceErrors `protobuf:"varint,2,opt,name=error,proto3,enum=rtuitlab.itlab.reports.v1.ReportsServiceErrors,oneof"`
}

func (*GetReportImplementerResp_Implementer) isGetReportImplementerResp_Result() {}

func (*GetReportImplementerResp_Error) isGetReportImplementerResp_Result() {}

type GetReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (x *GetReportReq) Reset() {
	*x = GetReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportReq) ProtoMessage() {}

func (x *GetReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportReq.ProtoReflect.Descriptor instead.
func (*GetReportReq) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP(), []int{2}
}

func (x *GetReportReq) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetReportResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*GetReportResp_Report
	//	*GetReportResp_Error
	Result isGetReportResp_Result `protobuf_oneof:"result"`
}

func (x *GetReportResp) Reset() {
	*x = GetReportResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResp) ProtoMessage() {}

func (x *GetReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResp.ProtoReflect.Descriptor instead.
func (*GetReportResp) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP(), []int{3}
}

func (m *GetReportResp) GetResult() isGetReportResp_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetReportResp) GetReport() *types.Report {
	if x, ok := x.GetResult().(*GetReportResp_Report); ok {
		return x.Report
	}
	return nil
}

func (x *GetReportResp) GetError() ReportsServiceErrors {
	if x, ok := x.GetResult().(*GetReportResp_Error); ok {
		return x.Error
	}
	return ReportsServiceErrors_REPORT_NOT_FOUND
}

type isGetReportResp_Result interface {
	isGetReportResp_Result()
}

type GetReportResp_Report struct {
	Report *types.Report `protobuf:"bytes,1,opt,name=report,proto3,oneof"`
}

type GetReportResp_Error struct {
	Error ReportsServiceErrors `protobuf:"varint,2,opt,name=error,proto3,enum=rtuitlab.itlab.reports.v1.ReportsServiceErrors,oneof"`
}

func (*GetReportResp_Report) isGetReportResp_Result() {}

func (*GetReportResp_Error) isGetReportResp_Result() {}

var File_rtuitlab_itlab_reports_v1_reports_proto protoreflect.FileDescriptor

var file_rtuitlab_itlab_reports_v1_reports_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2f, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x72, 0x74, 0x75, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x1a, 0x22, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2f, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64,
	0x22, 0x91, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6d,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x0b, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x12, 0x47, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2f, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x2b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49,
	0x64, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x47, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x72,
	0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x2a, 0x2c, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x50, 0x4f,
	0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x32, 0xea,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x7f, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x32, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x33, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5e, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x27, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x28, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x69, 0x5a, 0x3c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x54, 0x55, 0x49, 0x54, 0x4c,
	0x61, 0x62, 0x2f, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0xaa, 0x02, 0x28, 0x52, 0x54,
	0x55, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2e, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtuitlab_itlab_reports_v1_reports_proto_rawDescOnce sync.Once
	file_rtuitlab_itlab_reports_v1_reports_proto_rawDescData = file_rtuitlab_itlab_reports_v1_reports_proto_rawDesc
)

func file_rtuitlab_itlab_reports_v1_reports_proto_rawDescGZIP() []byte {
	file_rtuitlab_itlab_reports_v1_reports_proto_rawDescOnce.Do(func() {
		file_rtuitlab_itlab_reports_v1_reports_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtuitlab_itlab_reports_v1_reports_proto_rawDescData)
	})
	return file_rtuitlab_itlab_reports_v1_reports_proto_rawDescData
}

var file_rtuitlab_itlab_reports_v1_reports_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rtuitlab_itlab_reports_v1_reports_proto_goTypes = []interface{}{
	(ReportsServiceErrors)(0),        // 0: rtuitlab.itlab.reports.v1.ReportsServiceErrors
	(*GetReportImplementerReq)(nil),  // 1: rtuitlab.itlab.reports.v1.GetReportImplementerReq
	(*GetReportImplementerResp)(nil), // 2: rtuitlab.itlab.reports.v1.GetReportImplementerResp
	(*GetReportReq)(nil),             // 3: rtuitlab.itlab.reports.v1.GetReportReq
	(*GetReportResp)(nil),            // 4: rtuitlab.itlab.reports.v1.GetReportResp
	(*types.Report)(nil),             // 5: rtuitlab.itlab.reports.Report
}
var file_rtuitlab_itlab_reports_v1_reports_proto_depIdxs = []int32{
	0, // 0: rtuitlab.itlab.reports.v1.GetReportImplementerResp.error:type_name -> rtuitlab.itlab.reports.v1.ReportsServiceErrors
	5, // 1: rtuitlab.itlab.reports.v1.GetReportResp.report:type_name -> rtuitlab.itlab.reports.Report
	0, // 2: rtuitlab.itlab.reports.v1.GetReportResp.error:type_name -> rtuitlab.itlab.reports.v1.ReportsServiceErrors
	1, // 3: rtuitlab.itlab.reports.v1.Reports.GetReportImplementer:input_type -> rtuitlab.itlab.reports.v1.GetReportImplementerReq
	3, // 4: rtuitlab.itlab.reports.v1.Reports.GetReport:input_type -> rtuitlab.itlab.reports.v1.GetReportReq
	2, // 5: rtuitlab.itlab.reports.v1.Reports.GetReportImplementer:output_type -> rtuitlab.itlab.reports.v1.GetReportImplementerResp
	4, // 6: rtuitlab.itlab.reports.v1.Reports.GetReport:output_type -> rtuitlab.itlab.reports.v1.GetReportResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rtuitlab_itlab_reports_v1_reports_proto_init() }
func file_rtuitlab_itlab_reports_v1_reports_proto_init() {
	if File_rtuitlab_itlab_reports_v1_reports_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportImplementerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportImplementerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetReportImplementerResp_Implementer)(nil),
		(*GetReportImplementerResp_Error)(nil),
	}
	file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetReportResp_Report)(nil),
		(*GetReportResp_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtuitlab_itlab_reports_v1_reports_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtuitlab_itlab_reports_v1_reports_proto_goTypes,
		DependencyIndexes: file_rtuitlab_itlab_reports_v1_reports_proto_depIdxs,
		EnumInfos:         file_rtuitlab_itlab_reports_v1_reports_proto_enumTypes,
		MessageInfos:      file_rtuitlab_itlab_reports_v1_reports_proto_msgTypes,
	}.Build()
	File_rtuitlab_itlab_reports_v1_reports_proto = out.File
	file_rtuitlab_itlab_reports_v1_reports_proto_rawDesc = nil
	file_rtuitlab_itlab_reports_v1_reports_proto_goTypes = nil
	file_rtuitlab_itlab_reports_v1_reports_proto_depIdxs = nil
}
