// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: rtuitlab/itlab/salary/types.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityType int32

const (
	EntityType_UKNOWN   EntityType = 0
	EntityType_REPORT   EntityType = 1
	EntityType_EVENT    EntityType = 2
	EntityType_PROJECT  EntityType = 3
	EntityType_PURCHASE EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "UKNOWN",
		1: "REPORT",
		2: "EVENT",
		3: "PROJECT",
		4: "PURCHASE",
	}
	EntityType_value = map[string]int32{
		"UKNOWN":   0,
		"REPORT":   1,
		"EVENT":    2,
		"PROJECT":  3,
		"PURCHASE": 4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_rtuitlab_itlab_salary_types_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_rtuitlab_itlab_salary_types_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{0}
}

type VersionRole int32

const (
	VersionRole_WORKER      VersionRole = 0
	VersionRole_COORDINATOR VersionRole = 1
	VersionRole_RESPONSIBLE VersionRole = 2
)

// Enum value maps for VersionRole.
var (
	VersionRole_name = map[int32]string{
		0: "WORKER",
		1: "COORDINATOR",
		2: "RESPONSIBLE",
	}
	VersionRole_value = map[string]int32{
		"WORKER":      0,
		"COORDINATOR": 1,
		"RESPONSIBLE": 2,
	}
)

func (x VersionRole) Enum() *VersionRole {
	p := new(VersionRole)
	*p = x
	return p
}

func (x VersionRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionRole) Descriptor() protoreflect.EnumDescriptor {
	return file_rtuitlab_itlab_salary_types_proto_enumTypes[1].Descriptor()
}

func (VersionRole) Type() protoreflect.EnumType {
	return &file_rtuitlab_itlab_salary_types_proto_enumTypes[1]
}

func (x VersionRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionRole.Descriptor instead.
func (VersionRole) EnumDescriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{1}
}

type ReportEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (x *ReportEntity) Reset() {
	*x = ReportEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEntity) ProtoMessage() {}

func (x *ReportEntity) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEntity.ProtoReflect.Descriptor instead.
func (*ReportEntity) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{0}
}

func (x *ReportEntity) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type EventEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId     string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventRoleId string `protobuf:"bytes,2,opt,name=event_role_id,json=eventRoleId,proto3" json:"event_role_id,omitempty"`
	PlaceId     string `protobuf:"bytes,3,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *EventEntity) Reset() {
	*x = EventEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEntity) ProtoMessage() {}

func (x *EventEntity) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEntity.ProtoReflect.Descriptor instead.
func (*EventEntity) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{1}
}

func (x *EventEntity) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEntity) GetEventRoleId() string {
	if x != nil {
		return x.EventRoleId
	}
	return ""
}

func (x *EventEntity) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type PurchaseEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PurchaseId string `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
}

func (x *PurchaseEntity) Reset() {
	*x = PurchaseEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEntity) ProtoMessage() {}

func (x *PurchaseEntity) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEntity.ProtoReflect.Descriptor instead.
func (*PurchaseEntity) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{2}
}

func (x *PurchaseEntity) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type ProjectEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   string      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	VersionId   string      `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	TaskId      string      `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RoleId      string      `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	VersionRole VersionRole `protobuf:"varint,5,opt,name=version_role,json=versionRole,proto3,enum=rtuitlab.itlab.salary.VersionRole" json:"version_role,omitempty"`
}

func (x *ProjectEntity) Reset() {
	*x = ProjectEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEntity) ProtoMessage() {}

func (x *ProjectEntity) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEntity.ProtoReflect.Descriptor instead.
func (*ProjectEntity) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectEntity) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectEntity) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ProjectEntity) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProjectEntity) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ProjectEntity) GetVersionRole() VersionRole {
	if x != nil {
		return x.VersionRole
	}
	return VersionRole_WORKER
}

type Reason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType EntityType `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=rtuitlab.itlab.salary.EntityType" json:"entity_type,omitempty"`
	// Types that are assignable to Entity:
	//	*Reason_Report
	//	*Reason_Event
	//	*Reason_Purchase
	//	*Reason_Project
	Entity isReason_Entity `protobuf_oneof:"entity"`
}

func (x *Reason) Reset() {
	*x = Reason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reason) ProtoMessage() {}

func (x *Reason) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reason.ProtoReflect.Descriptor instead.
func (*Reason) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{4}
}

func (x *Reason) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_UKNOWN
}

func (m *Reason) GetEntity() isReason_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (x *Reason) GetReport() *ReportEntity {
	if x, ok := x.GetEntity().(*Reason_Report); ok {
		return x.Report
	}
	return nil
}

func (x *Reason) GetEvent() *EventEntity {
	if x, ok := x.GetEntity().(*Reason_Event); ok {
		return x.Event
	}
	return nil
}

func (x *Reason) GetPurchase() *PurchaseEntity {
	if x, ok := x.GetEntity().(*Reason_Purchase); ok {
		return x.Purchase
	}
	return nil
}

func (x *Reason) GetProject() *ProjectEntity {
	if x, ok := x.GetEntity().(*Reason_Project); ok {
		return x.Project
	}
	return nil
}

type isReason_Entity interface {
	isReason_Entity()
}

type Reason_Report struct {
	Report *ReportEntity `protobuf:"bytes,2,opt,name=report,proto3,oneof"`
}

type Reason_Event struct {
	Event *EventEntity `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type Reason_Purchase struct {
	Purchase *PurchaseEntity `protobuf:"bytes,4,opt,name=purchase,proto3,oneof"`
}

type Reason_Project struct {
	Project *ProjectEntity `protobuf:"bytes,5,opt,name=project,proto3,oneof"`
}

func (*Reason_Report) isReason_Entity() {}

func (*Reason_Event) isReason_Entity() {}

func (*Reason_Purchase) isReason_Entity() {}

func (*Reason_Project) isReason_Entity() {}

type Salary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId    string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ForUserId   string                 `protobuf:"bytes,4,opt,name=for_user_id,json=forUserId,proto3" json:"for_user_id,omitempty"`
	Reason      *Reason                `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Count       float64                `protobuf:"fixed64,6,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Salary) Reset() {
	*x = Salary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Salary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salary) ProtoMessage() {}

func (x *Salary) ProtoReflect() protoreflect.Message {
	mi := &file_rtuitlab_itlab_salary_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salary.ProtoReflect.Descriptor instead.
func (*Salary) Descriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_salary_types_proto_rawDescGZIP(), []int{5}
}

func (x *Salary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Salary) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Salary) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Salary) GetForUserId() string {
	if x != nil {
		return x.ForUserId
	}
	return ""
}

func (x *Salary) GetReason() *Reason {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *Salary) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Salary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_rtuitlab_itlab_salary_types_proto protoreflect.FileDescriptor

var file_rtuitlab_itlab_salary_types_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2f, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2f, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0c, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x31, 0x0a, 0x0e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x72,
	0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0xd8, 0x02,
	0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73,
	0x61, 0x6c, 0x61, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x06,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72,
	0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3a, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x74, 0x75,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x08, 0x70, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x72, 0x74, 0x75, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x48, 0x00, 0x52, 0x08, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73,
	0x61, 0x6c, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x08,
	0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x94, 0x02, 0x0a, 0x06, 0x53, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x2e,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a,
	0x4a, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x50,
	0x4f, 0x52, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x03, 0x12, 0x0c, 0x0a,
	0x08, 0x50, 0x55, 0x52, 0x43, 0x48, 0x41, 0x53, 0x45, 0x10, 0x04, 0x2a, 0x3b, 0x0a, 0x0b, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x4f,
	0x52, 0x4b, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4f, 0x52, 0x44, 0x49,
	0x4e, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x58, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x54, 0x55, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2f,
	0x49, 0x54, 0x4c, 0x61, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0xaa, 0x02,
	0x21, 0x52, 0x54, 0x55, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2e, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtuitlab_itlab_salary_types_proto_rawDescOnce sync.Once
	file_rtuitlab_itlab_salary_types_proto_rawDescData = file_rtuitlab_itlab_salary_types_proto_rawDesc
)

func file_rtuitlab_itlab_salary_types_proto_rawDescGZIP() []byte {
	file_rtuitlab_itlab_salary_types_proto_rawDescOnce.Do(func() {
		file_rtuitlab_itlab_salary_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtuitlab_itlab_salary_types_proto_rawDescData)
	})
	return file_rtuitlab_itlab_salary_types_proto_rawDescData
}

var file_rtuitlab_itlab_salary_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rtuitlab_itlab_salary_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rtuitlab_itlab_salary_types_proto_goTypes = []interface{}{
	(EntityType)(0),               // 0: rtuitlab.itlab.salary.EntityType
	(VersionRole)(0),              // 1: rtuitlab.itlab.salary.VersionRole
	(*ReportEntity)(nil),          // 2: rtuitlab.itlab.salary.ReportEntity
	(*EventEntity)(nil),           // 3: rtuitlab.itlab.salary.EventEntity
	(*PurchaseEntity)(nil),        // 4: rtuitlab.itlab.salary.PurchaseEntity
	(*ProjectEntity)(nil),         // 5: rtuitlab.itlab.salary.ProjectEntity
	(*Reason)(nil),                // 6: rtuitlab.itlab.salary.Reason
	(*Salary)(nil),                // 7: rtuitlab.itlab.salary.Salary
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_rtuitlab_itlab_salary_types_proto_depIdxs = []int32{
	1, // 0: rtuitlab.itlab.salary.ProjectEntity.version_role:type_name -> rtuitlab.itlab.salary.VersionRole
	0, // 1: rtuitlab.itlab.salary.Reason.entity_type:type_name -> rtuitlab.itlab.salary.EntityType
	2, // 2: rtuitlab.itlab.salary.Reason.report:type_name -> rtuitlab.itlab.salary.ReportEntity
	3, // 3: rtuitlab.itlab.salary.Reason.event:type_name -> rtuitlab.itlab.salary.EventEntity
	4, // 4: rtuitlab.itlab.salary.Reason.purchase:type_name -> rtuitlab.itlab.salary.PurchaseEntity
	5, // 5: rtuitlab.itlab.salary.Reason.project:type_name -> rtuitlab.itlab.salary.ProjectEntity
	6, // 6: rtuitlab.itlab.salary.Salary.reason:type_name -> rtuitlab.itlab.salary.Reason
	8, // 7: rtuitlab.itlab.salary.Salary.created_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_rtuitlab_itlab_salary_types_proto_init() }
func file_rtuitlab_itlab_salary_types_proto_init() {
	if File_rtuitlab_itlab_salary_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rtuitlab_itlab_salary_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_salary_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_salary_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_salary_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_salary_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtuitlab_itlab_salary_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Salary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rtuitlab_itlab_salary_types_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Reason_Report)(nil),
		(*Reason_Event)(nil),
		(*Reason_Purchase)(nil),
		(*Reason_Project)(nil),
	}
	file_rtuitlab_itlab_salary_types_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtuitlab_itlab_salary_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtuitlab_itlab_salary_types_proto_goTypes,
		DependencyIndexes: file_rtuitlab_itlab_salary_types_proto_depIdxs,
		EnumInfos:         file_rtuitlab_itlab_salary_types_proto_enumTypes,
		MessageInfos:      file_rtuitlab_itlab_salary_types_proto_msgTypes,
	}.Build()
	File_rtuitlab_itlab_salary_types_proto = out.File
	file_rtuitlab_itlab_salary_types_proto_rawDesc = nil
	file_rtuitlab_itlab_salary_types_proto_goTypes = nil
	file_rtuitlab_itlab_salary_types_proto_depIdxs = nil
}
