// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: rtuitlab/itlab/shared/ordering.proto

package shared

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ordering int32

const (
	Ordering_ASCENDING  Ordering = 0
	Ordering_DESCENDING Ordering = 1
)

// Enum value maps for Ordering.
var (
	Ordering_name = map[int32]string{
		0: "ASCENDING",
		1: "DESCENDING",
	}
	Ordering_value = map[string]int32{
		"ASCENDING":  0,
		"DESCENDING": 1,
	}
)

func (x Ordering) Enum() *Ordering {
	p := new(Ordering)
	*p = x
	return p
}

func (x Ordering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ordering) Descriptor() protoreflect.EnumDescriptor {
	return file_rtuitlab_itlab_shared_ordering_proto_enumTypes[0].Descriptor()
}

func (Ordering) Type() protoreflect.EnumType {
	return &file_rtuitlab_itlab_shared_ordering_proto_enumTypes[0]
}

func (x Ordering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ordering.Descriptor instead.
func (Ordering) EnumDescriptor() ([]byte, []int) {
	return file_rtuitlab_itlab_shared_ordering_proto_rawDescGZIP(), []int{0}
}

var File_rtuitlab_itlab_shared_ordering_proto protoreflect.FileDescriptor

var file_rtuitlab_itlab_shared_ordering_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2f, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2a, 0x29, 0x0a,
	0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x53, 0x43,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x53, 0x43,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x42, 0x74, 0x0a, 0x1b, 0x72, 0x74, 0x75, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x42, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e,
	0x67, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x54,
	0x55, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2f, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x3b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0xaa, 0x02, 0x1b, 0x52, 0x54, 0x55, 0x49, 0x54, 0x4c, 0x61, 0x62, 0x2e, 0x49, 0x54, 0x4c, 0x61,
	0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtuitlab_itlab_shared_ordering_proto_rawDescOnce sync.Once
	file_rtuitlab_itlab_shared_ordering_proto_rawDescData = file_rtuitlab_itlab_shared_ordering_proto_rawDesc
)

func file_rtuitlab_itlab_shared_ordering_proto_rawDescGZIP() []byte {
	file_rtuitlab_itlab_shared_ordering_proto_rawDescOnce.Do(func() {
		file_rtuitlab_itlab_shared_ordering_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtuitlab_itlab_shared_ordering_proto_rawDescData)
	})
	return file_rtuitlab_itlab_shared_ordering_proto_rawDescData
}

var file_rtuitlab_itlab_shared_ordering_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rtuitlab_itlab_shared_ordering_proto_goTypes = []interface{}{
	(Ordering)(0), // 0: rtuitlab.itlab.shared.Ordering
}
var file_rtuitlab_itlab_shared_ordering_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rtuitlab_itlab_shared_ordering_proto_init() }
func file_rtuitlab_itlab_shared_ordering_proto_init() {
	if File_rtuitlab_itlab_shared_ordering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtuitlab_itlab_shared_ordering_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtuitlab_itlab_shared_ordering_proto_goTypes,
		DependencyIndexes: file_rtuitlab_itlab_shared_ordering_proto_depIdxs,
		EnumInfos:         file_rtuitlab_itlab_shared_ordering_proto_enumTypes,
	}.Build()
	File_rtuitlab_itlab_shared_ordering_proto = out.File
	file_rtuitlab_itlab_shared_ordering_proto_rawDesc = nil
	file_rtuitlab_itlab_shared_ordering_proto_goTypes = nil
	file_rtuitlab_itlab_shared_ordering_proto_depIdxs = nil
}
